image: ghcr.io/astral-sh/uv:python3.13-trixie

cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - .cache/uv

variables:
  UV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/uv"

stages:
  - test

before_script:
  - uv sync --only-group dev
  - uv cache prune --ci
  # Already synced, no need to do it again on each `uv run` :)
  - export UV_NO_SYNC=1

test:formatting:
  stage: test
  script:
    - uv run ruff format --check .
    - uv run ruff check .
