image: python:3.7-buster

cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - .cache/pip
    - venv

stages:
  - test

before_script:
  - apt update
  - apt install -y python3-dev
  - pip install -U pip
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -U black isort

test:formatting:
  stage: test
  script:
    - black --check .
    - isort --check-only --diff .
